	.data



	.text


#---------------------------------------------------------------------------------

	.globl atribuicoes

atribuicoes:

	pushq %rbp

	movq  %rsp, %rbp


	# Se necessário, usar apenas os registradores (ou suas variações) abaixo:

	# %rax, %rcx, %rdx, %rdi, %rsi, %r8, %r9, %r10, %r11


	# Seu código aqui...


	leave

	ret


#---------------------------------------------------------------------------------

	.globl cast

cast:

	pushq %rbp

	movq  %rsp, %rbp


	# Se necessário, usar apenas os registradores (ou suas variações) abaixo:

	# %rax, %rcx, %rdx, %rdi, %rsi, %r8, %r9, %r10, %r11


	# Seu código aqui...


	leave

	ret


#---------------------------------------------------------------------------------

	.globl expressoes

expressoes:

	pushq %rbp

	movq  %rsp, %rbp


	# Se necessário, usar apenas os registradores (ou suas variações) abaixo:

	# %rax, %rcx, %rdx, %rdi, %rsi, %r8, %r9, %r10, %r11


	# Seu código aqui...


	leave

	ret


#---------------------------------------------------------------------------------

	.globl bitAbit

bitAbit:

	pushq %rbp

	movq  %rsp, %rbp


	# Se necessário, usar apenas os registradores (ou suas variações) abaixo:

	# %rax, %rcx, %rdx, %rdi, %rsi, %r8, %r9, %r10, %r11


	# Seu código aqui...


	leave

	ret


#---------------------------------------------------------------------------------

	.globl ponteiros

ponteiros:

	pushq %rbp

	movq  %rsp, %rbp


	# Se necessário, usar apenas os registradores (ou suas variações) abaixo:

	# %rax, %rcx, %rdx, %rdi, %rsi, %r8, %r9, %r10, %r11


	# Seu código aqui...


	leave

	ret