char proerd[] = {"Existe um programa\n"
"Que vai lhe ajudar\n"
"Existe um amigo\n"
"Que vai lhe ensinar\n"
"Que o problema drogas\n"
"Merece atenção\n"
"E pra manter-se a salvo\n"
"É preciso dizer não\n"
"\n"
"Proerd é o programa\n"
"Proerd é a solução\n"
"Lutando contra as drogas\n"
"Ensinando a dizer não\n"
"\n"
"Cultivando o amor próprio, controlando a tensão\n"
"Pensando nas consequências, resistindo a pressão\n"
"Como amar a própria vida\n"
"E às drogas dizer não\n"
"Quem lhe ensina é o amigo\n"
"Mas é sua decisão\n"
"\n"
"Proerd é o programa\n"
"Proerd é a solução\n"
"Lutando contra as drogas\n"
"Ensinando a dizer não\n"
"\n"
"Existe um programa\n"
"Que vai lhe ajudar\n"
"Existe um amigo\n"
"Que vai lhe ensinar\n"
"Que o problema drogas\n"
"Merece atenção\n"
"E para manter-se a salvo\n"
"É preciso dizer não\n"
"\n"
"Proerd é o programa\n"
"Proerd é a solução\n"
"Lutando contra as drogas\n"
"Ensinando a dizer não\n"
"\n"
"Cultivando o amor próprio, controlando a tensão\n"
"Pensando nas consequências, resistindo a pressão\n"
"Como amar a própria vida\n"
"E às drogas dizer não\n"
"Quem lhe ensina é o amigo\n"
"Mas é sua decisão\n"
"\n"
"Proerd é o programa\n"
"Proerd é a solução\n"
"Lutando contra as drogas\n"
"Ensinando a dizer não\n"};

char Michael[] = {"That's what she said.\n"};

char cachoro[] = {"Pode ser que um dia a gente se veja\n"
    "E passe a se falar\n"
    "Pode ser que um dia a gente se ame\n"
    "E case\n"
    "E tenha filhos\n"
    "E viaje pra Paris\n"
    "E assim vamos nós\n"
    "Ser felizes para sempre\n"
    "\n"
    "Mas pode ser também\n"
    "Que não dê em nada\n"
    "E que o nosso lance\n"
    "Seja só de uma noite\n"
    "De um dia ou de uma semana\n"
    "E depois cada um pra seu canto\n"
    "E fim de papo\n"
    "\n"
    "E pode ser também\n"
    "Que quando a gente se encontrar\n"
    "Não dê em nada\n"
    "E cada um vá pro seu lado\n"
    "E tudo bem\n"
    "\n"
    "Mas eu juro\n"
    "Eu juro que eu pensei\n"
    "Que eu fosse ficar\n"
    "Pra sempre do seu lado\n"
    "Eu juro\n"
    "Eu juro que eu pensei\n"
    "Que eu fosse ficar\n"
    "Pra sempre do seu lado\n"};

char Acabou[] = {"acabou\n"};